import { ITableConfig } from "./interfaces/component/ITableConfig";

export const defaultPersonTableConfigID = "justsomerandomidforspecifyingatableconfig";
export const defaultPersonTableConfig: ITableConfig = {
  id: defaultPersonTableConfigID,
  height: 600,
  headerHeight: 70,
  rowHeight: 30,
  name: "Person Table",
  columns: [
    {
      title: "Index",
      fieldName: "index",
      sortOrder: 0,
      sortable: false,
      width: 150,
      visible: true,
    },
    {
      title: "Name",
      fieldName: "name",
      sortOrder: 1,
      sortable: true,
      filterType: "input",
      width: 150,
      visible: true,
    },
    {
      title: "Email",
      fieldName: "email",
      sortOrder: 2,
      sortable: true,
      filterType: "input",
      width: 250,
      visible: true,
    },
    {
      title: "Age",
      fieldName: "age",
      sortOrder: 3,
      sortable: true,
      filterType: "input",
      width: 150,
      visible: true,
    },
    {
      title: "Gender",
      fieldName: "gender",
      sortOrder: 4,
      sortable: true,
      filterType: "select",
      width: 150,
      visible: true,
      filterOptions: [
        { label: "Male", value: "Male" },
        { label: "Female", value: "Female" },
      ],
    },
    {
      title: "Address",
      fieldName: "address",
      sortOrder: 5,
      sortable: true,
      filterType: "input",
      width: 150,
      visible: true,
    },
    {
      title: "City",
      fieldName: "city",
      sortOrder: 6,
      sortable: true,
      filterType: "input",
      width: 150,
      visible: true,
    },
    {
      title: "Postcode",
      fieldName: "postcode",
      sortOrder: 7,
      sortable: true,
      filterType: "input",
      width: 150,
      visible: true,
    },
    {
      title: "Country",
      fieldName: "country",
      sortOrder: 8,
      sortable: true,
      filterType: "input",
      width: 150,
      visible: true,
    },
  ],
};
