name: ChatGPT Review

on: [pull_request]

jobs:
  chatgpt-review:
    name: ChatGPT Review
    runs-on: ubuntu-latest
    steps:
      - uses: feiskyer/ChatGPT-Reviewer@latest
        name: ChatGPT Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
        with:
          model: "gpt-3.5-turbo"  # Specify the model if needed
          temperature: 0.2  # Adjust as required
          comment_per_file: true
